force-app/main/default/objects/Sample__c.object
<CustomObject>
    <label>Sample</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Sample Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Samples</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Test__c.object
<CustomObject>
    <description>All tests available at Wellness Labs</description>
    <fields>
        <fullName>Sample__c</fullName>
        <label>Sample</label>
        <referenceTo>Sample__c</referenceTo>
        <relationshipLabel>Tests</relationshipLabel>
        <relationshipName>Tests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Test</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/testCreatorHandler.cls
public class testCreatorHandler {
        public static void testCreation(List<Sample__c> sampleList) {
            List<Test__c> testList = new List<Test__c>(); 
            for(Sample__c s : sampleList) {
                Test__c newTest = new Test__c();
                newTest.Name = 'Default';
                newTest.Sample__c = s.Id;
                testList.add(newTest);

                
                
                }
                
                INSERT testList;
        }
    }
    
    

    